<h1>Termeni și conditii</h1>

<p>Platforma online Expert Independent are ca obiectiv simplificarea și automatizarea unui proces rezultat din necesitatea obținerii serviciului denumit: achiziționarea de materiale publicitare. Această nevoie se regăsește în principal la persoanele juridice dar nu numai.</p>
<p>Misiunea platformei, pe lângă obiectivul asumat de a automatiza întregul proces de achiziție de materiale publicitare, este de a oferi prin competiție deschisă servicii de design și grafică tot mai bune, dar și de a crea o comunitate de designeri competitivi. Se urmărește pe termen lung, ca efect al utilizării platformei, să crească accesibilitatea oricărei companii către grafică și design de calitate doar prin câteva clickuri distanță.</p>
<p>În vederea dezvoltării platformei online Expert Independent se vor identifica și modela cerințele funcționale prin intermediul diagramelor cazurilor de utilizare. Diagramele cazurilor de utilizare prezintă funcţionalităţile sistemului oferind o descriere generală a modului în care va fi utilizat sistemul de către actorii care interacționează cu acesta. Sistemul interactionează cu trei tipuri de actori: administratorul platformei, designer și client.</p> 
<p>Scenariul platformei este următorul: un antreprenor dorește crearea unui material publicitar (flyer,afiș, banner, pliant etc.). Clientul este cel care creează cont sau se loghează în platformă, introduce bugetul și cerințele, fișiere (precum logo, text, poze) și lansează un concurs cu deadline la care se vor înscrie designerii care au cont în platformă. Bugetul alocat proiectului va fi încasat inițial și aprobat de către platformă Aprobarea este necesară pentru a evita fraude. Are loc apoi o licitație de prețuri în care fiecare designer interesat de serviciul postat de client propune propriul preț de realizare. Clientul are la dispoziție 24 de ore să aleagă prețul final. În urma deciderii clientului asupra prețului final al serviciului, concursul începe. Această licitație de prețuri are loc în intervalul propus de client în momentul publicării serviciului în platformă.</p> 
<p>Designerii vor realiza fiecare câte un produs pe care îl vor uploada în platformă. Clientul are la dispoziție 10 zille după expirarea deadline-ului pentru a desemna un câștigător. De asemenea, clientul are posibilitatea să nominalizeze și câștigători secundari ai concursului, dacă soluțiile oferite de aceștia au fost bune pentru a-i stimula pe aceștia să participe la alte concursuri viitoare propuse de către clientul respectiv.</p>
<p>În cazul în care clientul nu va desemna un câștigător, bugetul încărcat în platformă va fi distribuit folosind următoarea distribuție: 10% din prețul final va fi distribuit paltformei, iar restul de 90% se vor reîntoarce în contul clientului în cazul în care acesta va aduce argumente relevante pentru decizia luată. Dacă însă decizia nu are argumente bine consolidate, 50% din prețul final se împarte între participanți, 10% procent standard îi revine platformei, iar clientului îi revin 40% din sumă.</p>
<p>În cazul desemnării unui câștigător, distribuirea bugetului se face folosind un algoritm menit să echilibreze și să motiveze participanții și să ofere puncte de feedback. Algoritmul de distribuire al sumei proiectului este complex și presupune luarea în considerare a mai multor criterii.</p>
<p>a) Desemnarea câștigătorilor presupune distribuția stelelor în funcție de nominalizările clienului. Câștigătorul (furnizorul proiectului) primește 5 stele (numărul maxim de stele pe care poate să îl primească un designer). Clientul poate desemna și alți câștigători de stele oferind un număr de stele între 1 și 4 din maximul de 20 pe care le are la dispoziție. De asemenea clientul poate desemna de asemenea pe cei care nu s-au încadrat în cerințele sale fiind considerați neconformi cu tema proiectului.</p>
<p>b) Distribuirea sumei presupune calculul procentelor raportate la suma proiectului  exprimate în valoare absolută. Astfel că platformei îi revine 10%, 70% din suma proiectului îi revine câștigătorului, iar 20% din suma alocată sunt împărțiți în funcție de numărul de stele acordate de către client celorlalți clienți. În cazul în care nu au fost desemnați și alți câștigători acești 20% îi revin câștigătorului, astfel acesta acumulează un procent de 90% din prețul final al concursului. Toate aceste reguli sunt consemnate în pagina de termeni și condiții cu care fiecare utilizator nou al platformei trebuie să fie de acord pentru a se putea înregistra.</p> 
<p>Mai departe, după obținerea graficii, clientul va putea downloada documentul pregătit pentru printare, va putea alege serviciile suplimentare puse la dispoziție de către platforma Expert Independent. În cazul în care clientul optează pentru aceste servicii, administratorul contactează tipografia parteneră. De asemenea clientul mai are posibilitatea de a opta pentru livrarea la domiciliu a produsului. Algoritmul de realizare este același – administratorul contactează curierul partener, iar acesta îi oferă informațiile referitoare la costurile serviciului. Apoi administratorul contactează clientul și îi furnizează informațiile legate de costul total al serviciilor suplimentare pentru care acesta a optat, urmând ulterior să plătească pentru acestea pentru confirmarea serviciilor.</p>
<p>Administratorul platformei are posibilitatea de a modifica statusul unui utilizator (client/designer) din activ în inactiv și invers. Tot el are posibilitatea de a modifica statusul unui concurs în finalizat în cazul în care un client ce a postat un anumit serviciu nu se ocupă de serviciu (nu alege preț, nu alege câștigător, etc.). Admin-ul este notificat asupra serviciilor suplimentare alese de client și are posibilitatea schimbării de informații cu acesta prin intermediul mesageriei. Administratorul este unic și este singurul ce are acces la statisticile aplicației.</p>


<?php


?>